version: '2.3'

services:
  statping:
    container_name: statpingng_statping
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8080:8080

volumes:
  statping_data:
